### ISSUE TITLE
Possibility for better design

### ISSUE THREAD

**Issue by AGVGA** [timburgan/timburgan#10932]
More than one person can perform any move for any given turn. And the GitHub actions bot will perform the move which is requested first among all the moves submitted by various persons in that turn. But the flaw here is that, each of these persons are considered to have taken the turn and are denied to play the next move. A better design would be to allow the players whose move in this turn is overrun (by the move displayed on the board for that turn) to also be eligible to play the next move.

**Comment by timburgan** [comment]
@AGVGA thank you. I'll hopefully have this improved in the next few weeks.
