### ISSUE TITLE
Feature to undo moves

### ISSUE THREAD

**Issue by myl989** [timburgan/timburgan#12171]
It would be nice if the moves could be undone before they take place, I often misclick but there is no way of undoing moves :)

**Comment by AGVGA** [comment]
Because this game is a real time experience, I think any feature that let's us undo moves would be problematic for everyone. The best we can do is to think clearly before performing any moves and enjoy the game!

**Comment by timburgan** [comment]
thank you @myl989, @AGVGA said it well.
