### ISSUE TITLE
Automatically flipping orientation of board for black turn

### ISSUE THREAD

**Issue by tanho63** [timburgan/timburgan#1228]
(?)

**Comment by timburgan** [comment]
That's a cool idea!

**Comment by Ghost-8D** [comment]
@timburgan I implemented this feature, should I send you a pull request? (There are two ways: 1. just reverse the rows and 2. reverse both rows and columns, which is what usually happens in real chess matches)

**Comment by tanho63** [comment]
Rows and cols :clap:

**Comment by Ghost-8D** [comment]
I sent a pull request to @timburgan with the enhancement. Let's hope he will accept it.
