### ISSUE TITLE
When a move is forced just take it

### ISSUE THREAD

**Issue by donno2048** [timburgan/timburgan#13960]
If there is only one possible move why wait for someone to commit it? Why not taking it automatically?

**Comment by donno2048** [comment]
cc @timburgan

**Comment by timburgan** [comment]
I've thought this too. Good idea.

**Comment by donno2048** [comment]
Do you plan to implement it? If not, I can submit a PR, it shouldn't be too hard, just take the move if there is only one move and set the last "player" to some dummy value (to allow the same person to play another move)

**Comment by donno2048** [comment]
cc @timburgan

**Comment by donno2048** [comment]
Stale...
