### ISSUE TITLE
Game stuck - Pawn promotion doesn't update board status

### ISSUE THREAD

**Issue by BurraAbhishek** [timburgan/timburgan#15810]
In #15806, I played h7-h8, intending to promote the pawn to a queen.

## What was expected:
Upon h7-h8, choose to promote to a queen, rook, bishop or knight. Whichever option I select, the pawn on h7 should go to h8 and then be replaced with the chosen piece. (In this case, I chose to promote to queen)

## What happened instead?
No change in board position, but the move was recorded as h8 instead of h8=Q in the PGN. No further move was possible.

cc @timburgan

**Comment by saberzero1** [comment]
I think I fixed the board for now with #15843 by manually making a move for the other side of the board. It probably doesn't fix the promotion problem described above, but at least unstuck the board.
