### ISSUE TITLE
Mobile looks wacky

### ISSUE THREAD

**Issue by ajmeese7** [timburgan/timburgan#1857]
![mobile](https://user-images.githubusercontent.com/17814535/87864282-07832280-c92c-11ea-8ba7-0bd5cdd19f3a.jpg)

I don't know if there's anything you can do about this, but on the GitHub app the "Start New Game" button is incredibly small, and the table squares are elongated so you have to do a lot of scrolling to see the entire board.

I know, it's crazy to use GitHub on mobile, but that's where I get notifications first. If it can't be fixed then no big, I just wanted to let you know. This is the most creative project I've seen in a long time, so thanks for the inspiration. Cheers!

cc @timburgan

**Comment by timburgan** [comment]
Me too. At the moment I appreciate GitHub Mobile app for the notification, but markdown rendering isnt the best yet. I do switch to a browser to see the game board.

**Comment by JJTech0130** [comment]
For me the game board looks normal, however, clicking on the links just opens the template selector![image](https://user-images.githubusercontent.com/53275876/151675769-8eaa1a77-b8d4-4b97-8b1a-346d6bd63304.png)

**Comment by JJTech0130** [comment]
For me the game board looks normal, however, clicking on the links just opens the template selector![image](https://user-images.githubusercontent.com/53275876/151675769-8eaa1a77-b8d4-4b97-8b1a-346d6bd63304.png)

**Comment by ajmeese7** [comment]
@JJTech0130 you're right! It looks much better now, I guess either Tim was able to fix it or GitHub improved the way they render their markdown on the app. Thanks for the update!

@timburgan as this now appears to be resolved I'm going to close out this issue, congrats on still having one of the coolest README's I've seen to date after several years have passed!
