### ISSUE TITLE
Nice Screenshot

### ISSUE THREAD

**Issue by BPower0036** [timburgan/timburgan#19473]
What do you think of this:
![afbeelding](https://user-images.githubusercontent.com/80090789/152357281-6611d027-aeeb-45ca-8de7-f7ffac3243e2.png)

**Comment by DalpatRathore** [comment]
Sorry! @BPower0036 this is a chess game, not a circus.

**Comment by BPower0036** [comment]
Sorry @DalpatRathore for doing it. I and @JohnyP36 tought that is would be nice for this one time.

**Comment by JohnyP36** [comment]
> Sorry! @BPower0036 this is a chess game, not a circus. cc @timburgan

Yes. 
And there are enough people who make this just a game of destroying as must pieces as the can, which is in my eyes not chess on a "high level". 
But maybe this happens, because there are a lot of different people with different views on the game.😀

**Comment by timburgan** [comment]
Thank you all for commenting and sharing in the community. This is a place for anyone to play a result for someone else to take the next turn. That can take many forms. 

Sometimes whole games are very high level, other times people learning chess for the first time, sometimes people who know nothing about chess and a just checking out what's going on here for any number of reasons. All of that is great and I'm excited for that.

As I've said before, I'm shocked this even still is played after I made it within a few hours for a challenge at work to experiment with GitHub profile pages when they were launched. The game as some hiccups in the current state given its growth. The fixes are "easy" but testing is a bit harder, again given the popularity and importance to many in the community. Stay tuned...

**Comment by DalpatRathore** [comment]
Sorry! won't bother anyone, enjoy playing.

_Stay happy & always blessed_

**Comment by timburgan** [comment]
Sorry all that the game is very stuck.... working on it
