### ISSUE TITLE
@JohnyP36 End last game

### ISSUE THREAD

**Issue by BPower0036** [timburgan/timburgan#19959]
@JohnyP36 This is how last game ended
![afbeelding](https://user-images.githubusercontent.com/80090789/154803021-7f415862-998f-4a17-85a4-cdc8c17a1bdb.png)

**Comment by JohnyP36** [comment]
@BPower0036 first time I (white) lost since playing. Congrats!

**Comment by BPower0036** [comment]
> @BPower0036 first time I (white) lost since playing. Congrats!

You forgot one time. It is the second time.
