### ISSUE TITLE
Looks like Top 20 Leaderboard has an issue

### ISSUE THREAD

**Issue by dr5hn** [timburgan/timburgan#2034]
@timburgan Top 20 Leaderboard :: It's adding count to someone else.

<img width="523" alt="Screenshot 2020-07-20 at 7 49 53 PM" src="https://user-images.githubusercontent.com/6929121/87948737-b5283a00-cac2-11ea-91fb-ba54dcbc39fd.png">

Issue within this..
https://github.com/timburgan/timburgan/blob/a3aacd89bbe240c59c9d83b71a8254faabd0d7fe/.github/workflows/chess.yml#L452-L465

**Comment by timburgan** [comment]
Yes it does lag by one move. Ì need to revisit the way I access the Issues API to count moves shortly. Thanks for letting me know
