### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by harshthakur9030** [timburgan/timburgan#2504]
Hey @timburgan, loved this. Could you please add some docs around how other could add use this?

**Comment by timburgan** [comment]
Thank you. Can you please explain more about what you mean?

**Comment by harshthakur9030** [comment]
I want to add this to my profile as well. What are the steps I need to take? For ex: Add a github token in github secrets.

**Comment by timburgan** [comment]
You don't need to change the GitHub Token. That's a special secret used with GitHub Actions:  
https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token

You should be able to just fork this repository, and yes, delete the `pgn` file. So it then appears on your GitHub Profile Readme, rename the repository to be `harshthakur9030`. 

I _think_ that's all that needs to be done. You may need to initiate the first game by creating an issue in your repository with the title, `chess|new`, but I can't quite recall.
