### ISSUE TITLE
Reduce emails when move is played

### ISSUE THREAD

**Issue by KhushrajRathod** [timburgan/timburgan#5414]
Hi,
For every move you play you get four emails

1. Issue comment
2. Issue closed
3. Commit message 1
4. Commit message 2

Is there anyway to reduce this?
Maybe only mention in one commit or don't mention in commits at all?

**Comment by timburgan** [comment]
Thanks for your suggestion! I've removed the mention in _Commit message 1_ and _Commit message 2_ in https://github.com/timburgan/timburgan/commit/5f0c2de60245bcef567079502fdf46c7d54ef7da
