### ISSUE TITLE
new move

### ISSUE THREAD

**Issue by rishik-00** [timburgan/timburgan#5490]

**Comment by sarveshggn** [comment]
Why are these issues open?
[Issue](https://github.com/timburgan/timburgan/issues/5490)
[Issue](https://github.com/timburgan/timburgan/issues/5489)
[Issue](https://github.com/timburgan/timburgan/issues/5487)
[Issue](https://github.com/timburgan/timburgan/issues/5486)
[Issue](https://github.com/timburgan/timburgan/issues/5482)
