### ISSUE TITLE
queen promotion game restart bug

### ISSUE THREAD

**Issue by thedoodler** [timburgan/timburgan#6411]
![image](https://user-images.githubusercontent.com/41851341/95318943-dc69f880-08b4-11eb-87d0-678e59ddcfae.png)

The game is still in progress but move options are for a new game

**Comment by thedoodler** [comment]
@timburgan

**Comment by timburgan** [comment]
Thanks for letting me know

**Comment by timburgan** [comment]
I've just reverted the problematic PR and the game is restarting now. Hopefully that's fixed it @thedoodler. Can you @ mention me again if not, thanks

**Comment by thedoodler** [comment]
awesome, it works thanks!
