### ISSUE TITLE
All jobs have failed

### ISSUE THREAD

**Issue by thedoodler** [timburgan/timburgan#7886]
there seems to be some issue with moving.  @timburgan 

<img width="1458" alt="Screenshot 2020-11-11 at 16 14 52" src="https://user-images.githubusercontent.com/41851341/98802265-0f198a80-2439-11eb-8940-d6db74e3a3ad.png">

**Comment by timburgan** [comment]
thanks for letting me know

**Comment by rahulxdd** [comment]
Still not fixed.

**Comment by timburgan** [comment]
Thanks, all fixed
