### ISSUE TITLE
It seems the game is "crashed" :(

### ISSUE THREAD

**Issue by michaelprimo** [timburgan/timburgan#8412]
Howdy cc @timburgan ,

We were playing Chess and for some reason I have to choose the beginning positions and not the actual positions to the game in progress, so... we can't proceed anymore. Can you unblock it? Thank you!

UPDATE: the game is unblocked, but anyway that bug is weird. I leave the issue just for telling you about it existence. Thank you again!

**Comment by timburgan** [comment]
![](https://i.giphy.com/media/jquDWJfPUMCiI/giphy.gif)

**Comment by timburgan** [comment]
@michaelprimo @JRetza I think the issue may be related to a GitHub Incident https://www.githubstatus.com/incidents/j4vrg2ljjb5c. It seems that may have just been resolved
