### ISSUE TITLE
contributing

### ISSUE THREAD

**Issue by NotAShelf** [timburgan/timburgan#8848]
hello,
I'm currently planning to make a fork of this repository in order to add a few small tweaks but it appears to me as if im unable to succesfully mimic the behaviour of this current version. is there a detailed list of what i need to change on the duplicate repository in order to be able to replicate the entire chess system within the seperate repository?

**Comment by michaelprimo** [comment]
Howdy,

I am only a user, not the main creatore of the repository. 

Try searching eventually settings. The game works because Github use Continuous Delivery on the main profile of the user, so try searching the github workflow folder and try to find more.

Have a good day!
