### ISSUE TITLE
Impossible moves

### ISSUE THREAD

**Issue by donno2048** [timburgan/timburgan#9654]
How could that even happen?
![image](https://user-images.githubusercontent.com/61805754/102556618-ffddca80-40d1-11eb-91fb-8bc79a38f0ed.png)
Two B2B3 in a row are impossible...
#9650 
#9652

**Comment by timburgan** [comment]
Hmm... looks like I need to update how that "last few moves" table is generated.

Looking at issues #9650 and #9652, I seems okay as #9650 wasn't a successful move.
